<?php

use Drupal\modal_delete_entity\Plugin\views\field\EntityDeleteModal;
use Drupal\modal_delete_entity\Plugin\views\field\EntityOperationsModal;
use Drupal\views\ViewExecutable;

/**
 * @file
 * Primary module hooks for modal_delete_entity module.
 */

///**
// * Implements hook_views_plugins_field_alter().
// */
//function modal_delete_entity_views_plugins_field_alter(array &$plugins) {
//  $plugins;
//}


/**
 * Implements hook_views_plugins_field_alter().
 */
function modal_delete_entity_views_plugins_field_alter(array &$plugins) {
  $plugins['entity_link_delete']['class'] = EntityDeleteModal::class;
  $plugins['entity_operations']['class'] = EntityOperationsModal::class;
}

function modal_delete_entity_preprocess_views_view_field(&$variables) {

}
